version: '3'

networks:
  my_network:
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server
    networks:
      my_network:
        ipv4_address: 172.18.0.3
    ports:
      - "8080:8080/udp"
    environment:
      SERVER_IP: "172.18.0.3"
      PORT: 8080
      BUFFER: 1024
      FREQUENCY: 10
    stdin_open: true
    tty: true

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: client
    networks:
      my_network:
        ipv4_address: 172.18.0.2
    environment:
      SERVER_IP: "172.18.0.3"
      PORT: 8080
      BUFFER: 1024
      FREQUENCY: 10
    depends_on:
      - server
    stdin_open: true
    tty: true