version: '3'

networks:
  my_network:

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server
    networks:
      - my_network
    ports:
      - "8080:8080/udp"

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: client
    networks:
      - my_network
    depends_on:
      - server
