version: '3'

networks:
  my_network:

services:
  server:
    build: ./server
    container_name: server
    networks:
      - my_network
    ports:
      - "8080:8080/udp"

  client:
    build: ./client
    container_name: client
    networks:
      - my_network
    depends_on:
      - server
